### ISSUE TITLE
Are cryptocurrencies supported by this library?

### ISSUE THREAD

**Issue by salvatorecapolupo** [florianv/swap#101]
Hello,

I was wondering if criptocurrencies (DASH, ETH, VTC,  XBC, XBT,BTC,XLM,XMR,XRP,ZEC as defined by standard ISO 4217) was supported, i.e:

$example = ( new Builder() )->add('fixer')->build();
$rate = $example->latest( 'BTC/EUR');

Actually it seems not working (btw they are actually showed in Yahoo Finance). Where could I find list of currencies OK with Swap?

**Comment by florianv** [comment]
@salvatorecapolupo You can use Cryptonator 

`$example = ( new Builder() )->add('cryptonator')->build();`

**Comment by salvatorecapolupo** [comment]
Btw, using:

```
	$swap = (new Builder())
    ->add('fixer')
    ->add('cryptonator')
    ->build();
```

you can support traditional and crypto together. Thanks very much!

**Comment by florianv** [comment]
Closing this ;)

**Comment by salvatorecapolupo** [comment]
I contacted original API developers fixer.io, and they say you maybe using legacy API of fixer, which does not support BTC.  Hope this could help improving next versions.
