### ISSUE TITLE
Google plugin stopped working

### ISSUE THREAD

**Issue by icaroscherma** [florianv/swap#102]
Error has already been quoted in #8 and #9 .
But I ran `composer update` and some laravel packages have been updated, but error is still happening :cry: 
```
Exchanger\Exception\ChainException with message 'The chain resulted in 1 exception(s):
Exchanger\Exception\Exception: The currency is not supported or Google changed the response format'
```

My code:
```PHP
$exchange = \Swap::latest('EUR/BRL')->getValue();
```

PS.: it WAS working until a few days ago, then only EUR started to give a headache after update I tried the `composer update` now in Tinker none works :sob: 

Btw, `composer update` (of SWAP part)
```Shell
  - Updating php-http/discovery (1.3.0 => 1.4.0): Downloading (100%)         
  - Updating florianv/exchanger (0.7.0 => 1.0.1): Downloading (100%)         
  - Updating florianv/swap (3.2.0 => 3.3.0): Downloading (100%)         
  - Updating florianv/laravel-swap (1.1.0 => 1.2.0): Downloading (100%)
```

**Comment by florianv** [comment]
@icaroscherma You can also update Exchange, it should be fixed now.

`composer update florianv/exchanger`
