### ISSUE TITLE
When google plugin throws exception most probably due to not finding a specific rate, it wont restore previous libxml_disable_entity_loader mode

### ISSUE THREAD

**Issue by FantomX1** [florianv/swap#103]
When google plugin throws exception, most probably due to not finding a specific rate, it won't restore previous libxml_disable_entity_loader mode, effectively disabling any further Soap operations, the 
`libxml_disable_entity_loader($disableEntities)`; restore operation is executed just after

**Comment by florianv** [comment]
Thanks for reporting this @FantomX1.

It is fixed in the latest version of Exchange. `composer update florianv/exchanger`

**Comment by FantomX1** [comment]
Thanks very much, maybe I haven't updated it for a longer period.
