### ISSUE TITLE
The "access_key" option must be provided to use fixer.io in project-files/vendor/florianv/exchanger/src/Service/Fixer.php:51

### ISSUE THREAD

**Issue by mukeshj17m** [florianv/swap#107]
As the fixer.io has changed it API and access_key is required. I am usign Laravel framework. I used "florianv/laravel-swap": "^1.1", and i updated the library today and now i can see one new constant ACCESS_KEY_OPTION = 'access_key' in florianv/exchanger/src/Service/Fixer.php ;
 It has these constants now: 
const ACCESS_KEY_OPTION = 'access_key';
const LATEST_URL = 'http://data.fixer.io/api/latest?base=%s&access_key=%s';
const HISTORICAL_URL = 'http://data.fixer.io/api/%s?base=%s&access_key=%s';

I have config/swap.php, i tried to pass it the access_key there but it doesnt work.
'currency_layer' => [
        'access_key' => '7ca208ea0d6d3323a14427bf9ed21',
        // 'enterprise' => true, // Tried also with enabling this.
 ],

 In config/services.php, i tried to pass it but still i can see the above error in laravel log. How to i pass the access_key.
'fixer' => [
        'access_key'     => '7ca208ea0d6d3323a14427bf9ed21'
    ],

How to i pass the access key, tried in many ways but its not working.

**Comment by florianv** [comment]
You ca now update Swap `composer update florianv/swap` and use the configuration provided in the documentation for Fixer's access key!

**Comment by mukeshj17m** [comment]
I got this error when I was using a free plan and using the base price as
USD but only EURO could be used as base price for free account. For others
currencies as base price we have to pay for the plan. The error is not
giving a proper information, that's why it is tricky to figure out what is
the issue.
