### ISSUE TITLE
Determine which service returned a rate

### ISSUE THREAD

**Issue by violuke** [florianv/swap#110]
Hi,

We're finding swap really useful, thanks. If we have a few services which can be used by swap, is there a way to know which service actually returned the rate in any particular instance?

Thanks for your help.

**Comment by florianv** [comment]
Hey @violuke,

thanks for your feedback!

Right now it's not possible, but it shouldn't be that hard to implement. What are you interested in the service name / class ?

**Comment by violuke** [comment]
Hey, thanks for the quick reply.

We're implementing a multi currency e-commerce application and will be storing daily rate snapshots. For historical and reporting purposes we'd like to know where rates actually came from. Some rates will have a legal obligation to come from the European Central Bank for tax reporting (but depending on the currencies involved in the sale, some will not).

So to answer your question it's really the service name (e.g. `European Central Bank` or `Google`) that we'd like, but anything that can allow us to pin point the source will be acceptable to the accounts department.

Thanks for your help.

**Comment by florianv** [comment]
Closing this in favor of the related Exchanger issue.
