### ISSUE TITLE
Suggestion for how to use with Money

### ISSUE THREAD

**Issue by sagikazarmark** [florianv/swap#12]
My Money representation of choice is https://github.com/mathiasverraes/money/. Do you have an idea how I could bring this library together with Swap?

I tried to find a way which uses swap's interfaces, but I couldn't find any without interface breaks.

**Comment by florianv** [comment]
You would like to convert from one Money to an other using Swap, right ?

**Comment by sagikazarmark** [comment]
Exactly. Or I would be happy, if I could get a Money CurrencyPair instead of a Rate object. I guess I will have to write a wrapper around swap.

**Comment by florianv** [comment]
I think it would be interesting to have a money converter in Swap.

We could create our own `Money` Value Object and a `ConverterInterface` with a `convert(Money $money, $currency)` method that returns a converted `Money` using `SwapInterface`.

Then we could have a Decorator that decorates the  `convert()` method to convert from mathiasverraes's Money to Swap's Money and vice versa.

**Comment by sagikazarmark** [comment]
> Then we could have a Decorator that decorates the  convert() method to convert from mathiasverraes's Money to Swap's Money and vice versa.

Isn't that an interface breaking implementation?

**Comment by florianv** [comment]
We could remove the typehints on the `convert()` method because we may support other money implementations.

Or we can have our own Money implementation and provide a factory that can create mathiasverraes's Money from Swap's Money and vice versa.

**Comment by sagikazarmark** [comment]
I think a Money ValueObject is out of scope for Swap. I really like it's simple architecture and single purpose. (Actually I think that even the CurrencyPair is not necessary => `quote($fromCurrency, $toCurrency)`, done). The rate is a valid object IMHO, since it is the result and has additional data.

A Converter interface is a good idea, but in that case Swap must be encapsulated in the converter.

**Comment by florianv** [comment]
> I think a Money ValueObject is out of scope for Swap

Yeah probably. But it would be nice to have a conversion feature because most people use the exchange rates value to convert from one money to an other in the end..

> A Converter interface is a good idea, but in that case Swap must be encapsulated in the converter.

Yes the `ConverterInterface` will depend on `SwapInterface`.

Maybe the easiest solution is simply to create a library that does the bridge between `Money` and `Swap`.

**Comment by sagikazarmark** [comment]
> Maybe the easiest solution is simply to create a library that does the bridge between Money and Swap.

That's in my mind as well.

**Comment by florianv** [comment]
I close this as it's not anymore related to this repo!

**Comment by florianv** [comment]
Ping me when you created this library, I can add a link to it in the README.

**Comment by sagikazarmark** [comment]
Will do. In the meantime: what's the purpose of `SwapInterface`? I mean, I don't really think that Swap should be reimplemented. If it is needed to be in some way (like in case of the bridge package), it won't necessarily be compatible with the interface.

**Comment by florianv** [comment]
`SwapInterface` is the contract that user code relies on. Swap is a specific implementation of `SwapInterface` with a provider system and a caching layer.

**Comment by sagikazarmark** [comment]
I see what it is, but is it really needed. Are there any real life use case for other swap implementations?

**Comment by florianv** [comment]
> but is it really needed?

Yes it serves as documentation of the public API, makes mocking easier for testing etc..
