### ISSUE TITLE
Final Swap cannot be mocked

### ISSUE THREAD

**Issue by willemstuursma** [florianv/swap#123]
Good day! We're in the process of implementing Swap. Thus far it's been great, but when writing the tests we want to mock out Swap (of course we don't want to get currency conversion rates from the internet during tests). 

Unfortunately Swap cannot be mocked because the class is declared `final`. 

We're now mocking `ExchangeRateProvider` which works but it relies on Swap internals to keep working in the future.

**Comment by florianv** [comment]
Hey @willemstuursma

Thanks for your feedback and report!

I think we can make the class public or we could also provide a `MockService` to use in tests

**Comment by willemstuursma** [comment]
Making `\Swap\Swap` non-`final` would be great and would allow easy mocking by anyone who uses is.

**Comment by florianv** [comment]
@willemstuursma Done and released!
