### ISSUE TITLE
Crypto currency converter

### ISSUE THREAD

**Issue by chateaux** [florianv/swap#125]
I am wondering if there is an out of the box exchanger for crypto?

If not, I do have rates from a number of vendors which are stored in a database. What would be the best way to include this in the class?

thank you.

**Comment by florianv** [comment]
@chateaux Hey, do have a `Cryptonator` service that retrieves rates from https://www.cryptonator.com.
If you want to use rates coming from your database, you can create a custom service class https://github.com/florianv/exchanger/tree/master/doc#creating-a-service

**Comment by chateaux** [comment]
Thank you for this.

I did create a CryptoNator account. It was not obvious how to use it though.

I will take a look at the "creating a service" class to see what I can do with that.

thank you for your time on this.
