### ISSUE TITLE
Update the quick start on the main page

### ISSUE THREAD

**Issue by PhoneixS** [florianv/swap#126]
In the web page, the commands for a quick start are:

`$ composer require florianv/swap php-http/message php-http/guzzle6-adapter`

But in the GitHub is:

`$ composer require php-http/curl-client nyholm/psr7 php-http/message florianv/swap`

which has the dependency `nyholm/psr7`.

I think the main web page should be updated.

**Comment by florianv** [comment]
@PhoneixS Done, thanks!
