### ISSUE TITLE
Exception when trying to convert to EUR with Google

### ISSUE THREAD

**Issue by TheAngelM97** [florianv/swap#129]
Everything was working well few days ago, but suddenly I when I try to format to EUR currency it throws an exception "the currency is not supported or google changed the response format".  Yes, I am using the google service, I searched and it seems this has happened before, why, is there any way I can fix it or will I have to wait for you t fix it or do I need to switch to fixer ?
PS: I tried composer update, didnt work, I am using USD to EUR conversion

**Comment by florianv** [comment]
@TheAngelM97 Unfortunately, we don't support the Google provider anymore, since the site has been unreliable and hard to maintain. Use Fixer ;)
