### ISSUE TITLE
New provider

### ISSUE THREAD

**Issue by sagikazarmark** [florianv/swap#13]
There is an Appspot API (which IMO uses the Google finance API):

http://currency-api.appspot.com/

**Comment by florianv** [comment]
Thanks for the suggestion, it could be interesting to implement

**Comment by florianv** [comment]
I'm closing this because I read on the website:

>* Absolutely NO WARRANTY regarding any aspect of the service - e.g its accuracy or reliability etc. is provided.

**Comment by sagikazarmark** [comment]
Oh, missed that.
