### ISSUE TITLE
[BUG] Exchange Rates API no longer working

### ISSUE THREAD

**Issue by srishaharidas** [florianv/swap#137]
Using the "exchange_rates_api" service no longer seems to be working.  This code now throws an error and complains about a missing access key:

``` 
        $converter = (new Builder())->add('exchange_rates_api')->build();
        $conversionRate = $converter->latest('USD/MXN')->getValue();
```
Looking at the latest documentation for Exchange Rates (https://exchangeratesapi.io/documentation/), they seem to now require an access key.

After obtaining an access key from https://exchangeratesapi.io/ tried fetching the conversion rate after including the access key but this doesnt seem to work. The below code still fails:

```
        $converter = (new Builder())->add('exchange_rates_api', ['access_key' => 'secret'])->build();
        $conversionRate = $converter->latest('USD/MXN')->getValue();
```

Dont think the current code handles an access key option for the exchange rates API.

**Comment by florianv** [comment]
Thanks @srishaharidas. I merged your PR in Exchanger, so it should be good to go!

**Comment by srishaharidas** [comment]
Awesome thanks for the update @florianv!
