### ISSUE TITLE
Are batch requests a possibility?

### ISSUE THREAD

**Issue by shawn-mollie** [florianv/swap#138]
Hi there, Is it a possibility now or in the future to query for multiple exchange rates in a single query to reduce calls?

**Comment by florianv** [comment]
Hi, unfortunately this feature isn't available yet since it requires to implement it in all services and required a lot of work..

**Comment by shawn-mollie** [comment]
Hi Florian, thanks for your response. Just so that I can try to assess the scale, could you briefly explain to me what "all services" means?
