### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by sagikazarmark** [florianv/swap#17]
I think caching is a great idea in this library, but I think caching should be transparent from Swap point of view.

I would implement a Cache provider which decorates other providers. This provider could accept another provider instance and an implementation of PSR-6 (although doctrine does not implement these interfaces, there are already quite good compatibility libraries: https://github.com/php-cache).

This way caching can be made optional (as it is now) and transparent from Swap's point of view.

WDYT? Would you accept a PR?

**Comment by florianv** [comment]
I agree we should use PSR-6 and the implementation you propose seems correct.

As per PHP Cache, there seems to be a Doctrine Cache implementation (https://github.com/php-cache/doctrine-adapter) but they miss an Illuminate Cache used by Swap's Laravel package.
