### ISSUE TITLE
Introducing HTTPlug

### ISSUE THREAD

**Issue by sagikazarmark** [florianv/swap#18]
Hey there,

Not sure you heard, but ivory http adapter is going to be deprecated in favor of [HTTPlug](http://httplug.io). There are many advantages in it over ivory. It is basically an HTTP abstraction layer (like ivory) and provides adapters (like ivory). A key difference is that it is an abstraction for CLIENTS, not adapters. So if one day a client decides to implement HTTPlug, the adapter can be deprecated.

We are also planning to submit it as a proposal for an HTTP Client PSR.

Would you be interested in a PR replacing ivory with httplug? Although it is not stable yet (RC1 currently) we plan to release a stable next week.

**Comment by florianv** [comment]
Hey @sagikazarmark,

> Not sure you heard, but ivory http adapter is going to be deprecated in favor of HTTPlug.

Yes I heard about it, it seems nice!

> Would you be interested in a PR replacing ivory with httplug? Although it is not stable yet (RC1 currently) we plan to release a stable next week.

Yes, thank you, if it can be done in a BC way.

**Comment by sagikazarmark** [comment]
> Yes, thank you, if it can be done in a BC way.

Well, replacing one library with another is not something that can easily be done in a BC way. Also, with the other three improvement ideas (interfaces, PSR-6 caching, transparent caching decorator) it probably worths to change the major version.

WDYT?

**Comment by florianv** [comment]
Once there is a stable release of `HTTPlug` we can indeed think about a new major version of Swap using it (including the features you suggested).

**Comment by phofmann-trust** [comment]
I just noticed that there's a stable version of php-http/httplug now.

**Comment by Nyholm** [comment]
Thank you @phofmann-trust, Ive added a PR now.
