### ISSUE TITLE
Drop Interface suffix

### ISSUE THREAD

**Issue by sagikazarmark** [florianv/swap#19]
I know it's a personal taste, but also a bullshit we learnt from Microsoft, Java, Symfony and the FIG, so I usualy try to convince people to drop it.

My main source is: http://verraes.net/2013/09/sensible-interfaces/

Although in your case it is probably harder, as you have an interface for the main entry point as well.

**Comment by florianv** [comment]
I agree it has some advantages to drop the interface suffix. I think it was also discussed in some Symfony projects as well.

> Although in your case it is probably harder, as you have an interface for the main entry point as well.

We could name the interface `Quoter` or `Exchanger` so we can still keep `Swap` as class name for the main implementation.
