### ISSUE TITLE
Generic HTTP Adapter library

### ISSUE THREAD

**Issue by sagikazarmark** [florianv/swap#2]
Hi there,

Currently I am working on a generic HTTP Client adapter library utilizing the upcoming PSR for HTTP Messages. I am reaching out for libraries I know whether there is interest for it or not. It collects the best pratices from competitors, and also based on a generic implementation instead of based on needs.

It is unclear where it will be published, but when it gets ready I will be more than happy to open a PR and integrate it into your package.

Are you interested?

**Comment by florianv** [comment]
I'm closing this issue as the version 2 relies on https://github.com/egeloen/ivory-http-adapter, which is also used by popular projects like https://github.com/geocoder-php/Geocoder.

**Comment by sagikazarmark** [comment]
Great, I love that adapter

**Comment by florianv** [comment]
:+1:

**Comment by sagikazarmark** [comment]
Update: ivory HTTP Adapter is going to be PHP HTTP Adapter (https://github.com/php-http). Probably it worth to rely on it in the next major version.

Documentation: http://php-http.readthedocs.org/

**Comment by sagikazarmark** [comment]
@florianv Would you accept a PR which prepares the change from Ivory HTTP Adapter to PHP HTTP? Since it is going to be deprecated.

**Comment by florianv** [comment]
Yes, I don't see any problem if it's implemented in a BC way.

Currently the only method used is `get()` https://github.com/florianv/swap/blob/master/src/Provider/AbstractProvider.php#L40.
