### ISSUE TITLE
Historical rates

### ISSUE THREAD

**Issue by florianv** [florianv/swap#21]
Some providers support retrieving historical rates, we should allow to do that for the providers support it.

**Comment by sagikazarmark** [comment]
I'm not sure, this seems to me out of scope. What would be the use case?

Whenever you need this data, it should be logged/stored instead of being retrieved from the past.

Just my two cents.

**Comment by marek-stopka** [comment]
@sagikazarmark and when you need to get the historic data to store them in a database, you suggest to create a separate library for it? I believe this library should do anything and everything that comes with exchange rates.

We have implemented a ČNB (Czech National Bank) interface (https://github.com/kramapet/swap/commit/fb18a0465655de33f63d716d8c18fdcc55871fc7) and we are planning to implement historical rates as a next step.

**Comment by sagikazarmark** [comment]
> you suggest to create a separate library for it?

Either a specific library or builtin in your application.

> I believe this library should do anything and everything that comes with exchange rates.

Definitely not, but I don't think you meant literally everything, did you? :smile: 

My problem with historical rates is that I think one cannot trust them. It is coming from the outside. If you don't work with rates regularly, it is acceptable to retrieve previous ones. But I guess it is not the case if you actually use this library.

My point is: I would rather store rates locally and rely on local data then relying on something coming from the outside (not to mention the HTTP call overhead).

I was probably not clear, sorry.

**Comment by florianv** [comment]
This feature was also suggested here https://github.com/florianv/laravel-swap/issues/13

**Comment by marek-stopka** [comment]
@kramapet will most probably implement this, both Generic API and history rates retrieval logic for CNB provider as we have it as a business requirement for our software.

**Comment by florianv** [comment]
Nice @marek-stopka @kramapet 👯 . 

Some suggestions:

I think receiving an optional `\DateTime` object to specify the rate date should be ok. 

Maybe a second parameter to exclude the time is needed. For example, I can ask the rate on `2014-05-05 00:00:00` but I don't care about the exact time, I'm just interested to get the rate that day.

If the provider does not support retrieving historical rates, an exception like `UnsupportedException` should be thrown.

**Comment by marek-stopka** [comment]
@florianv can you please assign @kramapet to this issue? I would say we should implement like this:

For `$rate->getValue('YYYY-MM-DD'); ` we either return a daily rate for that day if it is a daily constant rate or throw an error for daily moving rates and require exact time specification. What do you think?

**Comment by florianv** [comment]
> For $rate->getValue('YYYY-MM-DD'); we either return a daily rate for that day if it is a daily constant rate or throw an error for daily moving rates and require exact time specification. What do you think?

No, the rate is a value object. We need to accept a specific date in the `quote()` method instead. To avoid breaking BC we can accept a `QuotationRequest` object which would contain the currency pair and a date at which the rate must have be issued.

I think we need to even accept a minimum and maximum date for the historical rate. If the rate has been issued in this interval, then it's accepted; otherwise an exception is thrown.

I don't have any time in the near future to work on the specification or developing this feature.

**Comment by florianv** [comment]
I finally had the time to implement them in https://github.com/florianv/swap/pull/66. @sagikazarmark @avataru Feel free to check it
