### ISSUE TITLE
No definition found for Table yahoo.finance.xchange

### ISSUE THREAD

**Issue by moiroca** [florianv/swap#23]
No definition found for Table yahoo.finance.xchange

**Comment by diederikstuvia** [comment]
Same here, database down?

**Comment by moiroca** [comment]
@diederikstuvia 

I still have this issue but I temporarily fixed my issue by having a fallback using GoogleFinanceProvider instead of using YahooFinanceProvider. This might help you:

$chainProvider = new \Swap\Provider\ChainProvider([
    new \Swap\Provider\YahooFinanceProvider($httpAdapter),
    new \Swap\Provider\GoogleFinanceProvider($httpAdapter)
]);

Hope this issue will be fixed sooner!

**Comment by florianv** [comment]
Looks like the database is down yes. I tried to select values directly from their console and it failed.
Let's wait some time and see if this is a temporary problem.

In the meantime, you can use the solution suggested by @moiroca :+1:

**Comment by diederikstuvia** [comment]
Thanks guys! Works like a charm.

**Comment by florianv** [comment]
The issue seems to be fixed in Yahoo's end
