### ISSUE TITLE
Provide currency ISO codes as class constants

### ISSUE THREAD

**Issue by Ocramius** [florianv/swap#3]
As per http://www.reddit.com/r/PHP/comments/2s245t/swap_v2_exchange_rates_library_for_php/, this is a suggested improvement

**Comment by bojanz** [comment]
I think this library should avoid hardcoding the currency list at all (therefore removing the list in https://github.com/florianv/swap/blob/99d58b2778f6b4ccf8af0a7cf4542439b8bd793e/src/Util/CurrencyCodeValidator.php and just validating the format of the passed currency code).
The list of currencies is best left to other libraries, like symfony/intl.

The currency list used by Symfony and various ecommerce apps usually comes from CLDR, not ISO. CLDR includes historical currencies, which ISO doesn't. The historical currencies are still used mostly for currency conversion, for countries that switched currencies recently (like Latvia in 2014 and Lithuania in 2015).

**Comment by Ocramius** [comment]
@bojanz the main point is simply avoiding typos and providing quick autocompletion.

**Comment by florianv** [comment]
+1 for adding this enumeration of currency codes.

As @bojanz suggests, I'm going to remove the currency validator and let the provider fails if the currency is invalid. The currency validation is probably handled somewhere else before being passed to Swap.

**Comment by florianv** [comment]
In this [commit](https://github.com/florianv/swap/commit/9bb122b4e3d20a43e631d2e6721c03b874c1d5ad), I added an enumeration of the currency codes including the historical ones. I also removed the currency validation.

```php
use Swap\Util\CurrencyCodes;

$euroCode = CurrencyCodes::ISO_EUR;
$usdCode = CurrencyCodes::ISO_USD;
```

I had to prefix them with `ISO` because of the currency named `TRY`.

**Comment by Ocramius** [comment]
>  I also removed the currency validation.

Wasn't really needed, but thanks for including an enumeration: really makes it much harder to write a typo in there ;-)

**Comment by florianv** [comment]
@Ocramius thanks for the suggestion, it is indeed better with autocompletion :)
