### ISSUE TITLE
When base and quote currency are equal it throw exception

### ISSUE THREAD

**Issue by assaqqaf** [florianv/swap#31]
In google provider, when the base and quote currency are equal (EUR/EUR)., it throw ChainProviderException. because google converter didn't handle this case it return _Could not convert_.

it suppose to return 1 in this case.

http://www.google.com/finance/converter?a=1&from=EUR&to=EUR

it's only work with USD/USD:

http://www.google.com/finance/converter?a=1&from=USD&to=USD

**Comment by florianv** [comment]
Fixed in https://github.com/florianv/swap/pull/33
