### ISSUE TITLE
`Swap\Builder` could just be static

### ISSUE THREAD

**Issue by Ocramius** [florianv/swap#5]
There is no actual need for making `Swap\Builder` an instantiable class:

 * `$currencyConverter = Swap\Builder::fromYahooFinance();`
 * `$currencyConverter = Swap\Builder::fromGoogleFinance();`

These are perfectly fine. If multiple providers are required, then just allow constructor injection in the converter itself, which also plays better with other libraries willing to integrate Swap.

**Comment by florianv** [comment]
Thanks for the suggestion. It is also possible to specify a cache to use in the builder, for example:

```php
$swap = (new \Swap\Builder())
    ->yahooFinanceProvider()
    ->googleFinanceProvider()
    ->doctrineCache(new \Doctrine\Common\Cache\ApcCache(), 3600);
    ->build();
```

Because of that, I don't think we can make it static because it would have to be stateful which makes it harder to use.

**Comment by Ocramius** [comment]
I'd rather just make a compromise and make it a second argument or such.

**Comment by florianv** [comment]
I decided to remove the `Builder` in favor of manual construction. For simple cases, it is as hard as building `Swap` manually. If you want to pass a custom provider, you will need the `HttpAdapter` instance to create it, so the result won't be as simple as I initially thought. It is clearer and simpler to create the objects directly.

**Comment by florianv** [comment]
I'm closing this issue due to removal of the Builder. Thanks for your inputs @Ocramius
