### ISSUE TITLE
CurrencyCloud

### ISSUE THREAD

**Issue by HLFH** [florianv/swap#77]
Hi,

Could you support [CurrencyCloud](https://developer.currencycloud.com/documentation/api-docs/rates/get-rates-detailed/)?

Thanks,

**Comment by florianv** [comment]
Hello,

sure we are interested to support this service.

The repository containing all services is this one https://github.com/florianv/exchanger.

I don't think I will have enough time to implement it myself in the next days, but you could send a pull request.

The service creation is documented here https://github.com/florianv/exchanger/tree/master/doc#creating-a-service

Thanks!

**Comment by florianv** [comment]
Moved this to https://github.com/florianv/exchanger/issues/10
