### ISSUE TITLE
Support different currency

### ISSUE THREAD

**Issue by peter279k** [florianv/swap#81]
Is it possible to support different country currency?
For example, convert the USD dollars to TWD.

Thanks.

**Comment by florianv** [comment]
Yes, you can do `$rate = $swap->latest('USD/TWD')` for example.
The service you choose to build Swap needs to support these currencies but it's possible with `yahoo` or some commercial ones

**Comment by peter279k** [comment]
Hi @florianv, thank you for your comment.
I plan to develop the price game calculator so I need to the currency conversion services.
And the packages support many currency conversion services.
I notice that the ```Fixer``` service seems to support many currencies conversion.
Also your sample code in ```README``` uses the Fixer services to complete the currency conversion.

What do you think about the ```Fixer``` service?
Is this service enough for me? 

Thanks.

**Comment by florianv** [comment]
Hey @peter279k,

as far as I know `Fixer` is one of the best free services we have. There is also `Yahoo` which provides a lot of currencies. You can use them in a chain as shown in the documentation https://github.com/florianv/swap/blob/master/doc/readme.md#configuration
