### ISSUE TITLE
PHP Array support historical exchange rates

### ISSUE THREAD

**Issue by stefandoorn** [florianv/swap#82]
I'm currently working on a project where e.g. I need to convert COP -> EUR at historical rates. It seems that there is no provider out of the box capable of doing this. The PHP Array solution could serve as a backup if e.g. the project has them already in a database somewhere, providing an array looking like:

````
Array
(
    [2017-02-01] => Array
        (
            [COP/EUR] => new ExchangeRate(1.5)
        )

    [backup] => Array
        (
            [COP/EUR] => new ExchangeRate(2)
        )

)
````

The `backup` key could serve as a backup which is configurable, whether to use it or not.

Would such a PR be interesting to the project, or would it be rejected? I'm happy to submit one if there is interest.

**Comment by florianv** [comment]
Hey, if we add support to historical rates in the [PhpArray](https://github.com/florianv/exchanger/blob/master/src/Service/PhpArray.php#L25) service, I think it would solve your problem.

You could inject your backup rates, and declare the array provider at the end when building Swap

```php
$swap = (new Builder())
    ->add('fixer')
    ->add('array', [[], [// historical rates array here]])
    ->build();
```

**Comment by florianv** [comment]
Closing this issue in favor of https://github.com/florianv/swap/issues/88
