### ISSUE TITLE
Return 1 as exchange rate when currencies are identical

### ISSUE THREAD

**Issue by ruudk** [florianv/swap#83]
When I ask `Swap::latest('EUR/EUR')` for the latest exchange rate, it appears that it's actually contacting all the providers:

```
The chain resulted in 3 exception(s):
Exchanger\Exception\UnsupportedCurrencyPairException: The currency pair "EUR/EUR" is not supported by the service "Exchanger\Service\Fixer".
RuntimeException: Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON
Exchanger\Exception\UnsupportedCurrencyPairException: The currency pair "EUR/EUR" is not supported by the service "Exchanger\Service\EuropeanCentralBank".
```

This doesn't seem right to me. 

I looked at the code (both Swap and Exchanger) to see if I could create a PR to address this. I found out that in https://github.com/florianv/exchanger/blob/master/src/Exchanger.php#L46 it is smart enough to return `new ExchangeRate(1)` when the currencies are identical. 

I could add these checks to all `ExchangeRateProvider` implementations, but that does seem a bit ugly to me. What if an implementation forgets to add this. 

I could also add a check in `Swap\Swap::quote` to check if the currencies are identical. But the issue is that I need to use `Exchanger\CurrencyPair::createFromString` (instead of the contract `Exchanger\Contract\CurrencyPair` to use `CurrencyPair::isIdentical`.

What's your view on this?

**Comment by florianv** [comment]
Hey, Swap is not contacting any provider for identical currency pairs as you can see in this example:

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Swap\Builder;

// Build Swap with Fixer.io
$swap = (new Builder())
    ->add('fixer')
    ->add('yahoo')
    ->add('google')
    ->build();

$rate = $swap->latest('EUR/EUR');
```

**Comment by florianv** [comment]
@ruudk Maybe you are using an older version of `Exchanger` before the identical currency case was supported ?
