### ISSUE TITLE
Low value currencies should have their rates calculated inversely

### ISSUE THREAD

**Issue by andycansdale** [florianv/swap#85]
More of a suggestion rather than an issue...

When using a low value currency as the base currency, the rate returned from Yahoo and other providers is given to four decimal points and rounded. This can give some very big errors in the conversion.

It would be interesting to have some kind of table where if isLowValueBase == true, then the base and quote rates are swapped and the inverse of the resulting rate is served.

E.g.
**Colombian Peso => US Dollar (COP/USD)**
Rate given: 0.0003
**US Dollar => Colombian Peso (USD/COP)**
Rate given: 2,906.70

COP/USD calculated as inverse of USD/COP
0.000344 (to 6 decimal points)

COP/USD conversion with rates as given by provider for a house worth COP 1,000,000,000
COP 1,000,000,000 * 0.0003 = USD 300,000

COP/USD conversion with inverse of inverted rates for a house worth COP 1,000,000,000
COP 1,000,000,000 * 0.000344 = USD 344,000

$44,000 difference!!

I'm going to implement my own solution as above, storing currencies in an exchange_rates table and saving the inverted rate when needed, but I wonder if it might be a good idea to add this as a feature to Swap.

**Comment by florianv** [comment]
Hey @andycansdale,

I don't feel we need to add this feature to Swap as it's just a layer to fetch conversion rates from various providers.
