### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bool1993** [florianv/swap#90]
Fatal error: Uncaught exception 'Exchanger\Exception\ChainException' with message 'The chain resulted in 2 exception(s): Http\Client\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) Http\Client\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in F:\phpStudy\WWW\rate\vendor\florianv\exchanger\src\Service\Chain.php:66 Stack trace: #0 F:\phpStudy\WWW\rate\vendor\florianv\exchanger\src\Exchanger.php(56): Exchanger\Service\Chain->getExchangeRate(Object(Exchanger\ExchangeRateQuery)) #1 F:\phpStudy\WWW\rate\vendor\florianv\swap\src\Swap.php(91): Exchanger\Exchanger->getExchangeRate(Object(Exchanger\ExchangeRateQuery)) #2 F:\phpStudy\WWW\rate\vendor\florianv\swap\src\Swap.php(51): Swap\Swap->quote('EUR/USD', NULL, Array) #3 F:\phpStudy\WWW\rate\index.php(13): Swap\Swap->latest('EUR/USD') #4 {main} thr in F:\phpStudy\WWW\rate\vendor\florianv\exchanger\src\Service\Chain.php on line 66

**Comment by Ellrion** [comment]
Use this certificate root certificate bundle:

https://curl.haxx.se/ca/cacert.pem

Copy this certificate bundle on your disk. And use this on php.ini

curl.cainfo = "path_to_cert\cacert.pem"
