### ISSUE TITLE
Allow for PSR-16 caching mechanism

### ISSUE THREAD

**Issue by ddinchev** [florianv/swap#98]
Relying on PSR interfaces is great, however, PSR-6 was a bit controversial. It's a more involved interface and many popular frameworks have refused to implement it - so PSR-16 was introduced to allow for simplified caching systems.

Allowing for PSR-16 compatible cache systems would ease the integration of Swap with systems that rely on such systems. I'd introduce this by allowing `setHttpCachePool` and `setSimpleHttpCachePool`, with the later expecting `PSR-16`.

Internally, Exchanger would have its own Cache interface such that would simplify significantly the code of `Exchanger`, and two adapters, for PSR-6 and PSR-16 cache interfaces, which the adapters would wrap.

If you agree on the value of this and the rough implementation proposal, I would be happy to create a PR.

**Comment by florianv** [comment]
Hey @ddinchev, sure we will be interested in this! 
Feel free to start working on it and send a PR. 
Thanks

**Comment by florianv** [comment]
Closing this, since it has been added to the Exchanger repo instead.
